upstream changate {
    server 192.168.3.2:8080;
    keepalive 2;
}

server {
    listen 80;
    server_name changate.atompi.com;

    access_log /var/log/nginx/changate_302_access.log main;
    error_log /var/log/nginx/changate_302_error.log;

    return 302 https://$server_name$request_uri;
}

server {
    include ssl.d/atompi.com.conf; # https://github.com/atompi/SNIT
    server_name changate.atompi.com;

    access_log /var/log/nginx/changate_access.log main;
    error_log /var/log/nginx/changate_error.log;

    location / {
        proxy_pass http://changate;
        include core.d/proxy.conf; # https://github.com/atompi/SNIT
    }
}
